OUTPUT_DIR: "./logs/prw_coat"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/home/zqx_tesla/home/zqx_tesla/PersonReID/PersonReID2/SAT-main/data/PRW"
  BATCH_SIZE_TRAIN: 3
SOLVER:
  MAX_EPOCHS: 13
  BASE_LR: 0.003
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
DISP_PERIOD: 100
